'use strict';

cc.Lang = {
        missingVariantAttributeText: 'Bitte wählen Sie aus den fehlenden Attributen: ',
        noSelection: 'Keine Auswahl',
        pricePrefix:'',
        priceSuffix:' &euro;',
        pricePrefixLabel:'',
        priceSuffixLabel:' EUR',
        addToCart:'In den Warenkorb',
        backToCart:'Zurück zum Warenkorb',          // NEW
        nextStep:'nächster Schritt',                // NEW
        productTaxText:'inkl. {tax}% MwSt.',
        productDetails:'Information',
        productSpecifications:'Details',
        cartIsEmpty:'Ihr Warenkorb ist leer',
        cartInformation:'Information',
        cartQtyLabel:'Anzahl',
        cartSubtotal:'Zwischensumme',
        cartShipping:'Versand',
        cartTaxLabel:'enthaltene MwSt.',
        cartGrandTotalLabel:'Gesamtpreis',
        paymentMethodLabel:'Zahlungsmethode',
        otherPaymentMethod:'Andere Zahlung',
        paymentMethod: 'Zahlungsmethode',
        shippingMethod: 'Versand',
        cartBackToShopText:'Bitte nutzen Sie den normalen Online-Shop für weitere Zahlungsoptionen.<br><b>Achtung:</b> Sie verlieren Ihren aktuellen Warenkorb.',
        cartBackToShopLink:'Zum Online-Shop',
        regularPrice:'Regulärer Preis',
        btnYes:'Ja',
        btnNo:'Nein',
        btnOk:'Ok',
        btnCancel:'Abbrechen',
        btnDone: 'Fertig',
        btnWarning:'Achtung',
        cartDelMsg:'Sind Sie sicher, dass Sie das Produkt aus dem Warenkorb entfernen wollen?',
        /*checkout */
        waitGettingPaymentDetails:'Empfange Zahlungsdetails...',
        errorGettingPaymentDetails:'Fehler beim Empfangen der Zahlungsdetails.',
        waitFinishingOrder:'Fertigstellen der Bestellung ...',

        billingAddress:'Rechnungsadresse',
        shippingAddress:'Lieferadresse',
        billingMethod:'Zahlungsmethode',
        formAddress:'Adresse',
        formCompany:'Firma',
        formSurname:'Name',
        formGivenName:'Vorname',
        formStreet:'Strasse / Nummer',
        formCity:'Wohnort',
        formZip:'PLZ',
        formCountry:'Land',
        formEmail:'E-mail Adresse',
        formTelephone:'Telefonnummer',
        shippongMethod:'Versand',
        listItemQty:'Anzahl:',
        listItemPrice:'Einzelpreis:',
        listItemSubtotal:'Summe:',
        summaryQtyLabel:'Anzahl',
        summarySubtotal:'Gesamtpreis der Ware',
        summaryShipping:'Versandkosten',
        summaryTaxLabel:'enthaltene MwSt.',
        summaryGrandTotalLabel:'Gesamtpreis',


        buyButton:'Kaufen',                         // NEW

        generalAgreement:'Die <a href="javascript:void(0);" id="agblink">AGB</a> habe ich zur Kenntnis genommen und bin mit ihrer Geltung einverstanden.',
        recallAgreement:'Die <a href="javascript:void(0);" id="widerruflink">Widerrufsbelehrung</a> habe ich zur Kenntnis genommen.',
        ageAgreement:'Hiermit bestätige ich, dass ich 18 Jahre alt (oder älter) bin.',
        confirmAgreement:'Bitte bestätigen Sie, dass Sie die AGB und Widerrufsbelehrung gelesen und zur Kenntnis genommen haben.',
        combinedAgreement:'Ich stimme den <a href="javascript:void(0);" id="agblink">AGB</a> zu und habe die <a href="javascript:void(0);" id="widerruflink">Informationen zum Widerrufsrecht</a> gelesen.',

        /*thank you*/
        thankYouTitle:'Danke für Ihren Einkauf bei uns!',
        thankTouText:'Sie bekommen in Kürze eine Bestätigungsmail',
        continueShopping:'Weiter einkaufen',
        productMaxLimitHit: 'Sie haben die maximale Menge für dieses Produkt erreicht',
        back: 'zurück',
        pages: 'Seiten',
        soldOut: 'ausverkauft',
        pleaseWait: 'bitte warten',
        checkout: 'Checkout',
        surChargeWarning:'Es fallen zusätzliche Gebühren in Höhe von {surcharge} an',
        surcharge:'Zusätzliche Gebühren',
        // This is temporally disabled until we use the new
        // checkout process
        paymentMethod_paypalexpress: 'PayPal',
        paymentMethod_prepayment: 'Vorauszahlung',
        paymentMethod_invoice: 'Rechnung',
        paymentMethod_paymentOnDelivery: 'Nachnahme',
        paymentMethod_others: 'Andere Zahlung',
        showProducts: 'Produkte anzeigen',
        showProductsInfo: 'Die aktuelle Kategorie enthält sowohl Unterkategorien als auch direkt zugewiesene Produkte. In der aktuellen Ansicht werden Ihnen nur die Unterkategorien dargestellt. Tippen Sie auf <b>Produkte anzeigen</b>, wenn Sie stattdessen die Produkte dieser Kategorie sehen möchten',
        whatDoesThatMean: 'Was bedeutet das?',
        shoppingCart: 'Warenkorb',
        summary: 'Zusammenfassung',
        pageDoesntExist: 'Diese Seite existiert nicht',
        nonEUInfo: 'Bei Lieferung in das Nicht-EU-Ausland können zusätzliche Zölle, Steuern und Gebühren anfallen',
        choose: 'wähle',
        invalidInput_Firstname: 'Bitte geben Sie Ihren Vornamen ein',
        invalidInput_Lastname: 'Bitte geben Sie Ihren Nachnamen ein',
        invalidInput_Street: 'Bitte geben Sie Ihre Straße ein',
        invalidInput_Zip: 'Bitte geben Sie Ihre PLZ ein',
        invalidInput_City: 'Bitte geben Sie Ihren Wohnort ein',
        invalidInput_Country: 'Bitte geben Sie Ihre Land ein',
        invalidInput_Email: 'Bitte geben Sie eine gültige E-Mail Adresse ein',
        welcomeText: 'Willkommen im Couch Demo Shop',
        showDesktopView:'Web-App verlassen'
    };