#!/bin/sh

# return 1 if global command line program installed, else 0
# example
# echo "node: $(program_is_installed node)"
function program_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  type $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

# display a message in red with a cross by it
# example
# echo echo_fail "No"
function echo_fail {
  # echo first argument in red
  printf "\e[31m✘ ${1}"
  # reset colours back to normal
  echo "\033[0m"
}

# display a message in green with a tick by it
# example
# echo echo_fail "Yes"
function echo_pass {
  # echo first argument in green
  printf "\e[32m✔ ${1}"
  # reset colours back to normal
  echo "\033[0m"
}

function echo_green {
  printf "\e[32m${1}"
  echo "\033[0m"
}

if [ $(program_is_installed npm) != 1 ]
    then
        echo_fail "Can't start installation \n  ERROR: Missing 'npm' command, make sure to install node first.";
        exit
fi

if [ $(program_is_installed bower) != 1 ]
    then
        echo_fail "Can't start installation \n  ERROR: Missing 'bower' command, make sure to install bower first.";
        exit

fi

echo_pass "npm installed";
echo_pass "bower installed";
echo_green "  Installing node dependencies...";
npm install
echo_pass "node dependencies installed"
echo_green "  Installing bower dependencies...";
bower install
echo_pass "bower dependencies installed"
echo_pass "Dependencies installed successfully"
echo_green "Starting app at localhost port 9000..."
grunt watch
